version: '3.7'

services:
  logseq-publish-spa:
    image: ghcr.io/l-trump/logseq-publish-spa:alpine
    ## Build by yourself
    # build:
    #   context: .
    #   dockerfile: Dockerfile.alpine
    environment:
      PUB_THEME: light
      # PUB_ACCENT_COLOR: blue
      # PUB_GRAPH_DIR: /graph
      # PUB_OUT_DIR: /out
    volumes:
      - ./graph:/graph:ro
      - ./out:/out
